FROM sandwichimg/alpine:armhf-edge

COPY mkimage /mkimage
COPY repositories /etc/apk/repositories

ENV DISTRO=alpine \
    DESKTOP=base \
    ARCH=armhf \
    BRANCH=edge \
    DEVICE=rpi

RUN apk --update --no-cache add uboot-tools dosfstools e2fsprogs parted findutils util-linux tar zip vim
RUN apk add --no-cache ca-certificates wget && update-ca-certificates

CMD ["/mkimage"]
