FROM multiarch/alpine:aarch64-edge as qemu

FROM arm64v8/debian:stretch-slim

COPY --from=qemu /usr/bin/qemu-* /usr/bin

ENV DEBIAN_FRONTEND=noninteractive

RUN set -xe \
  && apt-get update \
  && apt-get install --no-install-recommends -y libguestfs-tools zip wget xxd u-boot-tools \
  && rm -rf /var/lib/apt/lists/*
